//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AskGenerator.Helpers {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MailsData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailsData() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AskGenerator.Helpers.MailsData", typeof(MailsData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;h1&gt;Вітаємо!&lt;/h1&gt;
        ///
        ///&lt;p&gt;Вашу електронну адресу було викоритсано для реєстрації на сайті &lt;em&gt;&lt;a href=&quot;[siteURL]&quot; title=&quot;NoM&quot;&gt;[siteName]&lt;/a&gt;&lt;/em&gt;.&lt;/p&gt;
        ///
        ///&lt;p&gt;Щоб завершити реєстрацію перейдіть за наступним посиланням &lt;a href=&quot;[confirmURL]&quot;&gt;[confirmURL]&lt;/a&gt;&lt;/p&gt;
        ///
        ///&lt;p&gt;Якщо ви не проходили реєстрацію, будь ласка, проігноруйте цей лист.&lt;/p&gt;
        ///
        ///&lt;hr /&gt;
        ///&lt;p&gt;&lt;strong&gt;N&lt;/strong&gt;etwork &lt;strong&gt;o&lt;/strong&gt;f &lt;strong&gt;M&lt;/strong&gt;entors&lt;/p&gt;.
        /// </summary>
        internal static string ConirmRegistration_Body {
            get {
                return ResourceManager.GetString("ConirmRegistration_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вітаємо!
        ///
        ///Вашу електронну адресу було викоритсано для реєстрації на сайті [siteName].
        ///
        ///Щоб завершити реєстрацію перейдіть за наступним посиланням [confirmURL]
        ///
        ///Якщо ви не проходили реєстрацію, будь ласка, проігноруйте цей лист.
        ///
        ///Network of Mentors.
        /// </summary>
        internal static string ConirmRegistration_Plain {
            get {
                return ResourceManager.GetString("ConirmRegistration_Plain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Завершіть реєстрацію..
        /// </summary>
        internal static string ConirmRegistration_Subj {
            get {
                return ResourceManager.GetString("ConirmRegistration_Subj", resourceCulture);
            }
        }
    }
}
