//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AskGenerator.Business.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зв&apos;язок з нами.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        public static string AccountId {
            get {
                return ResourceManager.GetString("AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Студент&quot; повино бути заповнене.
        /// </summary>
        public static string AccountIdRequired {
            get {
                return ResourceManager.GetString("AccountIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати кафедру.
        /// </summary>
        public static string AddDepartment {
            get {
                return ResourceManager.GetString("AddDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + додати групу.
        /// </summary>
        public static string AddGroup {
            get {
                return ResourceManager.GetString("AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати запитання.
        /// </summary>
        public static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати студента.
        /// </summary>
        public static string AddStudent {
            get {
                return ResourceManager.GetString("AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати викладача.
        /// </summary>
        public static string AddTeacher {
            get {
                return ResourceManager.GetString("AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Відповіть.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Відповіть&quot; повино бути заповнене.
        /// </summary>
        public static string AnswerRequired {
            get {
                return ResourceManager.GetString("AnswerRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до списку.
        /// </summary>
        public static string BackToTheList {
            get {
                return ResourceManager.GetString("BackToTheList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://halloffame-networkofmentors.rhcloud.com/.
        /// </summary>
        public static string bestURL {
            get {
                return ResourceManager.GetString("bestURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Рейтинг викладачів.
        /// </summary>
        public static string Board {
            get {
                return ResourceManager.GetString("Board", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На вказану вами електронну адресу буде надіслано лист, для закінчення реєстраціі..
        /// </summary>
        public static string CheckPost {
            get {
                return ResourceManager.GetString("CheckPost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скинути.
        /// </summary>
        public static string Clean {
            get {
                return ResourceManager.GetString("Clean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Очистити форму.
        /// </summary>
        public static string CleanForm {
            get {
                return ResourceManager.GetString("CleanForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Підтвердіть, що ви не робот..
        /// </summary>
        public static string ConfirmNoRobot {
            get {
                return ResourceManager.GetString("ConfirmNoRobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити кафедру.
        /// </summary>
        public static string CreateDepartment {
            get {
                return ResourceManager.GetString("CreateDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створити групу.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення питання.
        /// </summary>
        public static string CreateQuestion {
            get {
                return ResourceManager.GetString("CreateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення студента.
        /// </summary>
        public static string CreateStudent {
            get {
                return ResourceManager.GetString("CreateStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Створення викладача.
        /// </summary>
        public static string CreatreTeacher {
            get {
                return ResourceManager.GetString("CreatreTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дані станом на.
        /// </summary>
        public static string DataFrom {
            get {
                return ResourceManager.GetString("DataFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедри.
        /// </summary>
        public static string Departments {
            get {
                return ResourceManager.GetString("Departments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Опис.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заватнажити файл.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати аккаунт.
        /// </summary>
        public static string EditAccount {
            get {
                return ResourceManager.GetString("EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагувати кафедру.
        /// </summary>
        public static string EditDepartment {
            get {
                return ResourceManager.GetString("EditDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування групи.
        /// </summary>
        public static string EditGroup {
            get {
                return ResourceManager.GetString("EditGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування питання.
        /// </summary>
        public static string EditQuestion {
            get {
                return ResourceManager.GetString("EditQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування студента.
        /// </summary>
        public static string EditStudent {
            get {
                return ResourceManager.GetString("EditStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Редагування викладача.
        /// </summary>
        public static string EditTeacher {
            get {
                return ResourceManager.GetString("EditTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Електронна адреса.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ця адреса вже використовується.
        /// </summary>
        public static string EmailIsUsed {
            get {
                return ResourceManager.GetString("EmailIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; повинне бути довжиною {1}.
        /// </summary>
        public static string ExactLenghtError {
            get {
                return ResourceManager.GetString("ExactLenghtError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string facebook {
            get {
                return ResourceManager.GetString("facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.facebook.com/semka148.
        /// </summary>
        public static string fbURL {
            get {
                return ResourceManager.GetString("fbURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ім&apos;я.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Ім&apos;я&quot; повино бути заповнене.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evaluator.
        /// </summary>
        public static string Generator {
            get {
                return ResourceManager.GetString("Generator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Группа.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва групи.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкажіть группу у якій навчається студент.
        /// </summary>
        public static string GroupRequired {
            get {
                return ResourceManager.GetString("GroupRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Групи.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пояснення найвищої оцінки.
        /// </summary>
        public static string HigherRateDescription {
            get {
                return ResourceManager.GetString("HigherRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Пояснення найвищої оцінки&quot; повино бути заповнене.
        /// </summary>
        public static string HigherRateDescriptionRequired {
            get {
                return ResourceManager.GetString("HigherRateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фотографія.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Завантажте будь-ласка фотографію.
        /// </summary>
        public static string ImageRequired {
            get {
                return ResourceManager.GetString("ImageRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index.
        /// </summary>
        public static string IndexHeader {
            get {
                return ResourceManager.GetString("IndexHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Це запитання стосується викладача?.
        /// </summary>
        public static string IsAboutTeacher {
            get {
                return ResourceManager.GetString("IsAboutTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Це запитання стосується викладача?&quot; повино бути заповнене.
        /// </summary>
        public static string IsAboutTeacherRequired {
            get {
                return ResourceManager.GetString("IsAboutTeacherRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запам`ятати мене.
        /// </summary>
        public static string IsPersistent {
            get {
                return ResourceManager.GetString("IsPersistent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ключ.
        /// </summary>
        public static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прізвище.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Фамілія&quot; повино бути заповнене.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лівий ліміт.
        /// </summary>
        public static string LeftLimit {
            get {
                return ResourceManager.GetString("LeftLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ліміти.
        /// </summary>
        public static string Limits {
            get {
                return ResourceManager.GetString("Limits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список кафедр.
        /// </summary>
        public static string ListDepartments {
            get {
                return ResourceManager.GetString("ListDepartments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список груп.
        /// </summary>
        public static string ListGroup {
            get {
                return ResourceManager.GetString("ListGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Лист запитань.
        /// </summary>
        public static string ListQuestion {
            get {
                return ResourceManager.GetString("ListQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список студентів.
        /// </summary>
        public static string ListStudents {
            get {
                return ResourceManager.GetString("ListStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список викладачів.
        /// </summary>
        public static string ListTeachers {
            get {
                return ResourceManager.GetString("ListTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вхід.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вихід.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пояснення найнижчої оцінки.
        /// </summary>
        public static string LowerRateDescription {
            get {
                return ResourceManager.GetString("LowerRateDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Пояснення найнижчої оцінки&quot; повино бути заповнене.
        /// </summary>
        public static string LowerRateDescriptionRequired {
            get {
                return ResourceManager.GetString("LowerRateDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semka148@rambler.ru.
        /// </summary>
        public static string mail {
            get {
                return ResourceManager.GetString("mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *My MVC Admin Template.
        /// </summary>
        public static string MyMVCAdminTemplate {
            get {
                return ResourceManager.GetString("MyMVCAdminTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Група.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва.
        /// </summary>
        public static string NameDepart {
            get {
                return ResourceManager.GetString("NameDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Група&quot; повино бути заповнене.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова кафедра.
        /// </summary>
        public static string NewDepartment {
            get {
                return ResourceManager.GetString("NewDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нова група.
        /// </summary>
        public static string NewGroup {
            get {
                return ResourceManager.GetString("NewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нове запитання.
        /// </summary>
        public static string NewQuestion {
            get {
                return ResourceManager.GetString("NewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий студент.
        /// </summary>
        public static string NewStudent {
            get {
                return ResourceManager.GetString("NewStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новий викладач.
        /// </summary>
        public static string NewTeacher {
            get {
                return ResourceManager.GetString("NewTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ні.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введене прізвище не знайдено у вказаній групі або вже використовується.
        /// </summary>
        public static string NoLastNameFound {
            get {
                return ResourceManager.GetString("NoLastNameFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoM.
        /// </summary>
        public static string nom {
            get {
                return ResourceManager.GetString("nom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://nom-http://nom-networkofmentors.rhcloud.com/.
        /// </summary>
        public static string nomURL {
            get {
                return ResourceManager.GetString("nomURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паролі не співпадаюсь.
        /// </summary>
        public static string NoRepitPassword {
            get {
                return ResourceManager.GetString("NoRepitPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ще не зареєстровані?.
        /// </summary>
        public static string NotRegistred {
            get {
                return ResourceManager.GetString("NotRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стара кафедра.
        /// </summary>
        public static string OldDepartment {
            get {
                return ResourceManager.GetString("OldDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Стара група.
        /// </summary>
        public static string OldGroup {
            get {
                return ResourceManager.GetString("OldGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старе запитання.
        /// </summary>
        public static string OldQuestion {
            get {
                return ResourceManager.GetString("OldQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старий викладач.
        /// </summary>
        public static string OldTeacher {
            get {
                return ResourceManager.GetString("OldTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Або введіть Ваш ключ.
        /// </summary>
        public static string OrEnterTheKey {
            get {
                return ResourceManager.GetString("OrEnterTheKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +38(097)-87-30-150.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фото.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питання про викладачів.
        /// </summary>
        public static string QuestionAbTeacher {
            get {
                return ResourceManager.GetString("QuestionAbTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запитання.
        /// </summary>
        public static string QuestionBody {
            get {
                return ResourceManager.GetString("QuestionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Запитання&quot; повино бути заповнене.
        /// </summary>
        public static string QuestionBodyRequired {
            get {
                return ResourceManager.GetString("QuestionBodyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Номер запитання.
        /// </summary>
        public static string QuestionId {
            get {
                return ResourceManager.GetString("QuestionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Номер запитання&quot; повино бути заповнене.
        /// </summary>
        public static string QuestionIdRequired {
            get {
                return ResourceManager.GetString("QuestionIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перестворити ключі.
        /// </summary>
        public static string RegenerateLoginKeys {
            get {
                return ResourceManager.GetString("RegenerateLoginKeys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви закінчили реєстрацію, тепер ви можете увiйти.
        /// </summary>
        public static string RegisterFinish {
            get {
                return ResourceManager.GetString("RegisterFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реєстрація користувача.
        /// </summary>
        public static string RegisterUser {
            get {
                return ResourceManager.GetString("RegisterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Некоректна ареса.
        /// </summary>
        public static string RegularAddress {
            get {
                return ResourceManager.GetString("RegularAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введіть валідну группу.
        /// </summary>
        public static string RegularGroup {
            get {
                return ResourceManager.GetString("RegularGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторіть  пароль.
        /// </summary>
        public static string RepitPassword {
            get {
                return ResourceManager.GetString("RepitPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; повинно бути заповнене.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Правий ліміт.
        /// </summary>
        public static string RightLimit {
            get {
                return ResourceManager.GetString("RightLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зберігти.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть кафедру.
        /// </summary>
        public static string SelectDepartment {
            get {
                return ResourceManager.GetString("SelectDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виберіть группу.
        /// </summary>
        public static string SelectGroup {
            get {
                return ResourceManager.GetString("SelectGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибріть групи.
        /// </summary>
        public static string SelectGroups {
            get {
                return ResourceManager.GetString("SelectGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оставим это на память)).
        /// </summary>
        public static string SomethingElseHere {
            get {
                return ResourceManager.GetString("SomethingElseHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студент.
        /// </summary>
        public static string Student {
            get {
                return ResourceManager.GetString("Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенти.
        /// </summary>
        public static string Students {
            get {
                return ResourceManager.GetString("Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач.
        /// </summary>
        public static string Teacher {
            get {
                return ResourceManager.GetString("Teacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дошка вчителів.
        /// </summary>
        public static string TeacherBoard {
            get {
                return ResourceManager.GetString("TeacherBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладач.
        /// </summary>
        public static string TeacherId {
            get {
                return ResourceManager.GetString("TeacherId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &quot;Викладач&quot; повино бути заповнене.
        /// </summary>
        public static string TeacherIdRequired {
            get {
                return ResourceManager.GetString("TeacherIdRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Викладачі.
        /// </summary>
        public static string Teachers {
            get {
                return ResourceManager.GetString("Teachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Студенти викладача.
        /// </summary>
        public static string TeacherStudent {
            get {
                return ResourceManager.GetString("TeacherStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кафедра.
        /// </summary>
        public static string Team {
            get {
                return ResourceManager.GetString("Team", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назва кафедри.
        /// </summary>
        public static string TeamName {
            get {
                return ResourceManager.GetString("TeamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переключення навігації.
        /// </summary>
        public static string ToggleNavigation {
            get {
                return ResourceManager.GetString("ToggleNavigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тултіп.
        /// </summary>
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поле &apos;{0}&apos; повинне бути довжиною від {2} до {1}.
        /// </summary>
        public static string ValidLenght {
            get {
                return ResourceManager.GetString("ValidLenght", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VK.
        /// </summary>
        public static string vk {
            get {
                return ResourceManager.GetString("vk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/dekanatfikt.
        /// </summary>
        public static string vkdekURL {
            get {
                return ResourceManager.GetString("vkdekURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://vk.com/semka148.
        /// </summary>
        public static string vkURL {
            get {
                return ResourceManager.GetString("vkURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Проголосувало {0} студентів.
        /// </summary>
        public static string VotedStudentsFormat {
            get {
                return ResourceManager.GetString("VotedStudentsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сторінка голосування.
        /// </summary>
        public static string VotePage {
            get {
                return ResourceManager.GetString("VotePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Голосування.
        /// </summary>
        public static string Voting {
            get {
                return ResourceManager.GetString("Voting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вітаємо!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Працювали для вас.
        /// </summary>
        public static string workforyou {
            get {
                return ResourceManager.GetString("workforyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірна електронна адреса чи пароль.
        /// </summary>
        public static string WrongEmailOrPassword {
            get {
                return ResourceManager.GetString("WrongEmailOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Невірний ключ. Спробуйте увійти за допомогою логіна або зареєструватись..
        /// </summary>
        public static string WrongLoginKey {
            get {
                return ResourceManager.GetString("WrongLoginKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Так.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
