// <auto-generated />
namespace AskGenerator.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class QuestionsOrder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(QuestionsOrder));
        
        string IMigrationMetadata.Id
        {
            get { return "201603231615597_QuestionsOrder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
