// <auto-generated />
namespace AskGenerator.DataProvider.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Faculties : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Faculties));
        
        string IMigrationMetadata.Id
        {
            get { return "201605181959260_Faculties"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
